global:
  # >>> Execute the following command to receive the domain:
  # $ kubectl get gateway -n kyma-system kyma-gateway -o jsonpath='{.spec.servers[0].hosts[0]}'
  # Remove the leading "*."
  domain: null
  imagePullSecret:
    name: container-registry
hana_deployer:
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/bookshop-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: bookshop-db
html5_apps_deployer:
  cloudService: java.bookshop
  backendDestinations:
    bookshop-srv:
      service: srv
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/bookshop-html5-deployer
    tag: latest
srv:
  bindings:
    db:
      fromSecret: bookshop-db
  image:
    # >>> Replace <your-container-registry> with your container registry
    repository: <your-container-registry>/bookshop-srv
    tag: latest
  env:
    SPRING_PROFILES_ACTIVE: cloud
    BP_JVM_VERSION: 17
    BP_JVM_TYPE: JRE
  resources:
    limits:
      cpu: 2000m
      ephemeral-storage: 1G
      memory: 2G
    requests:
      cpu: 1000m
      ephemeral-storage: 1G
      memory: 2G
